### ISSUE TITLE
Wordpress source 

### ISSUE THREAD

**Issue by pmonty** [samfromaway/nextjs-apollo#1]
Hi I have a wordpress site with WPGraphql installed. Would it work if I have my url inserted into this?

All examples so far I have found seem to use something other than Wordpress.

**Comment by pmonty** [comment]
@samfromaway sorry was in a bit of a rush yesterday when posting. Basically most tutorials when I use them with nextjs and apollo they use some custom fetch method to call the graphql instead when using WPGraphql plugin in wordpress. But for me it just doesn't seem to work locally. I am not sure if it is my local wordpress site or doing it like your codebase is setup doesn't work for a wordpress cms and needs a nexus schema?

**Comment by samfromaway** [comment]
@pmonty Unfortunately I don't have experience with WPGraphql. What I can say is that as soon as you have access to the api from WP that gives you a JSON you can access it via the next.js fetch methods.
